tags:
  - name: Session
    description: Session endpoints.

components:
  schemas:
    Session:
      type: object
      properties:
        id:
          type: number
          example: 1
        browser:
          type: string
          example: Firefox
        os:
          type: string
          example: Linux
        created_at:
          type: string
          example: 2021-01-01T00:00:00.000Z
        expire_at:
          type: string
          example: 2021-01-01T00:00:00.000Z
        is_active:
          type: boolean
          example: false

    ClearSessions:
      type: object
      properties:
        clear_active:
          type: boolean
          example: false

    SessionsResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/Session'
        message:
          type: string
          example: نشست‌ها با موفقیت دریافت شدند.

    SessionResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          $ref: '#/components/schemas/Session'
        message:
          type: string
          example: نشست با موفقیت دریافت شد.

    DeleteSessionResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: نشست حذف شد.

    ClearSessionResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: تمام نشست‌ها حذف شدند.

    NotFoundSessionResponse:
      description: Not Found.
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: number
                example: 404
              error:
                type: string
                example: نشست یافت نشد.

paths:
  /session:
    get:
      summary: Get all sessions.
      tags: [Session]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionsResponse'
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'

  /session/clear:
    post:
      summary: Clear all sessions.
      tags: [Session]
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClearSessions'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ClearSessions'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClearSessionResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: فیلد پاک کردن نشست فعال باید یک boolean باشد.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'

  /session/{id}:
    get:
      summary: Get a session by id.
      tags: [Session]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the session.
          schema:
            type: number
            example: 1
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        404:
          $ref: '#/components/schemas/NotFoundSessionResponse'

    delete:
      summary: Delete a session by id.
      tags: [Session]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the session.
          schema:
            type: number
            example: 1
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteSessionResponse'
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        404:
          $ref: '#/components/schemas/NotFoundSessionResponse'
        409:
          description: Conflict.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 409
                  error:
                    type: string
                    example: امکان حذف نشست فعال وجود ندارد.
