tags:
  - name: Authentication
    description: Authentication endpoints.

components:
  schemas:
    Login:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        password:
          type: string
          example: password
          minLength: 8
          maxLength: 32
      required:
        - email
        - password

    Register:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        password:
          type: string
          example: password
          minLength: 8
          maxLength: 32
        otp:
          type: string
          example: '12345'
          minLength: 5
          maxLength: 5
      required:
        - email
        - password
        - otp

    Recover:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        password:
          type: string
          example: password
          minLength: 8
          maxLength: 32
        otp:
          type: string
          example: '12345'
          minLength: 5
          maxLength: 5
      required:
        - email
        - password
        - otp

    SendOtp:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@example.com
      required:
        - email

    VerifyOtp:
      type: object
      properties:
        email:
          type: string
          format: email
          example: test@example.com
        otp:
          type: string
          example: '12345'
          minLength: 5
          maxLength: 5
      required:
        - email
        - otp

    VerifyEmailOtp:
      type: object
      properties:
        otp:
          type: string
          example: '12345'
          minLength: 5
          maxLength: 5
      required:
        - otp

    LoginResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: object
          properties:
            email:
              type: string
              format: email
              example: test@example.com
            token:
              type: string
              example: token
        message:
          type: string
          example: ورود با موفقیت انجام شد.

    RegisterResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 201
        data:
          type: object
          properties:
            email:
              type: string
              format: email
              example: test@example.com
        message:
          type: string
          example: ثبت‌نام با موفقیت انجام شد.

    SendOtpResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: object
          properties:
            email:
              type: string
              format: email
              example: test@example.com
        message:
          type: string
          example: کد تایید ارسال شد.

    RecoverResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: object
          properties:
            email:
              type: string
              format: email
              example: test@example.com
        message:
          type: string
          example: کد تایید ارسال شد.

    VerifyOtpResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: object
          properties:
            email:
              type: string
              format: email
              example: test@example.com
            is_verified:
              type: boolean
              example: true
        message:
          type: string
          example: کد تایید شد.

    VerifyEmailResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: object
          properties:
            is_email_verified:
              type: boolean
              example: true
        message:
          type: string
          example: ایمیل تایید شد.

    ManyRequestResponse:
      description: Too Many Requests.
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: number
                example: 429
              error:
                type: string
                example: لطفا ۶۰ ثانیه دیگر دوباره تلاش کنید.

paths:
  /auth/login:
    post:
      summary: Login a user.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل یا گذرواژه نادرست است.
        403:
          description: Forbidden.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 403
                  error:
                    type: string
                    example: کاربر غیرفعال می‌باشد.

  /auth/register:
    post:
      summary: Register a new user.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
      responses:
        201:
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل نادرست است.

  /auth/register/send-otp:
    post:
      summary: Send OTP to email.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendOtp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendOtp'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendOtpResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل نادرست است.
        429:
          $ref: '#/components/schemas/ManyRequestResponse'

  /auth/register/verify-otp:
    post:
      summary: Verify OTP.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyOtp'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOtpResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: کد تایید معتبر نمی‌باشد.

  /auth/recover:
    post:
      summary: Recover a user.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recover'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Recover'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecoverResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل نادرست است.

  /auth/recover/send-otp:
    post:
      summary: Send OTP to email.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendOtp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SendOtp'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendOtpResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل نادرست است.
        429:
          $ref: '#/components/schemas/ManyRequestResponse'

  /auth/recover/verify-otp:
    post:
      summary: Verify OTP.
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyOtp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyOtp'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOtpResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: کد تایید معتبر نمی‌باشد.

  /auth/verify-email/send-otp:
    post:
      summary: Send OTP to email.
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: کد تایید ارسال شد.
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: ایمیل نادرست است.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        429:
          $ref: '#/components/schemas/ManyRequestResponse'

  /auth/verify-email/verify-otp:
    post:
      summary: Verify email.
      tags: [Authentication]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyEmailOtp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/VerifyEmailOtp'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyEmailResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: کد تایید معتبر نمی‌باشد.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'

  /auth/logout:
    delete:
      summary: Logout a user.
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 200
                  message:
                    type: string
                    example: خروج از حساب کاربری با موفقیت انجام شد.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
