components:
  schemas:
    Pagination:
      type: object
      properties:
        page:
          type: number
          example: 1
        pages:
          type: number
          example: 2
        next_page:
          type: number
          nullable: true
          example: 2
        prev_page:
          type: number
          nullable: true
          example: null
        limit:
          type: number
          example: 20
        total:
          type: number
          example: 32
  
  parameters:
    PaginationPage:
      name: page
      in: query
      required: false
      description: Page number to retrieve.
      schema:
        type: number
        example: 1
    
    PaginationLimit:
      name: limit
      in: query
      required: false
      description: Maximum items per page.
      schema:
        type: number
        example: 20