tags:
  - name: Activity
    description: Activity endpoints.

components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: Hiking
        image:
          type: string
          example: https://example.com/photo.webp
        created_at:
          type: string
          example: 2021-01-01T00:00:00.000Z

    CreateActivity:
      type: object
      properties:
        name:
          type: string
          example: Hiking
        image:
          type: string
          format: binary
      required:
        - name
        - image

    UpdateActivity:
      type: object
      properties:
        name:
          type: string
          example: Hiking
        image:
          type: string
          format: binary

    ActivitiesResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        pagination:
          $ref: '#/components/schemas/Pagination'
        message:
          type: string
          example: Activities retrieved successfully.

    CreatedActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: Activity created successfully.

    UpdateActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: Activity updated successfully.

    DeleteActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: Activity deleted successfully.

paths:
  /activity:
    get:
      summary: Get all activities.
      tags: [Activity]
      parameters:
        - $ref: '#/components/parameters/PaginationPage'
        - $ref: '#/components/parameters/PaginationLimit'
        - $ref: '#/components/parameters/OrderBy'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesResponse'

    post:
      summary: Create a activity.
      tags: [Activity]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateActivity'
      responses:
        201:
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedActivityResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: Invalid name or image.
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 401
                  error:
                    type: string
                    example: Access denied. Authentication is required.

  /activity/{id}:
    patch:
      summary: Update a activity.
      tags: ['Activity']
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the activity.
          schema:
            type: number
            example: 1
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateActivity'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateActivityResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: Invalid name or image.
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 401
                  error:
                    type: string
                    example: Access denied. Authentication is required.

    delete:
      summary: Delete a activity.
      tags: ['Activity']
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the activity.
          schema:
            type: number
            example: 1
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteActivityResponse'
        401:
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 401
                  error:
                    type: string
                    example: Access denied. Authentication is required.
        404:
          description: Not Found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 404
                  error:
                    type: string
                    example: Activity not found.
