tags:
  - name: Activity
    description: Activity endpoints.

components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: Hiking
        image:
          type: string
          example: https://example.com/photo.webp
        created_at:
          type: string
          example: 2021-01-01T00:00:00.000Z

    CreateActivity:
      type: object
      properties:
        name:
          type: string
          example: Hiking
        image:
          type: string
          format: binary
      required:
        - name
        - image

    UpdateActivity:
      type: object
      properties:
        name:
          type: string
          example: Hiking
        image:
          type: string
          format: binary

    ActivitiesResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        data:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        pagination:
          $ref: '#/components/schemas/Pagination'
        message:
          type: string
          example: فعالیت‌ها با موفقیت دریافت شدند.

    CreateActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 201
        message:
          type: string
          example: فعالیت ایجاد شد.

    UpdateActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: فعالیت بروزرسانی شد.

    DeleteActivityResponse:
      type: object
      properties:
        status_code:
          type: number
          example: 200
        message:
          type: string
          example: فعالیت حذف شد.

    ActivityNotFoundResponse:
      description: Not Found.
      content:
        application/json:
          schema:
            type: object
            properties:
              status_code:
                type: number
                example: 404
              error:
                type: string
                example: فعالیت یافت نشد.


paths:
  /activity:
    get:
      summary: Get all activities.
      tags: [Activity]
      parameters:
        - $ref: '#/components/parameters/PaginationPage'
        - $ref: '#/components/parameters/PaginationLimit'
        - $ref: '#/components/parameters/OrderBy'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesResponse'

    post:
      summary: Create a activity.
      tags: [Activity]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateActivity'
      responses:
        201:
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateActivityResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: نام باید رشته باشد.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        403:
          $ref: '#/components/schemas/ForbiddenResponse'

  /activity/{id}:
    patch:
      summary: Update a activity.
      tags: ['Activity']
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the activity.
          schema:
            type: number
            example: 1
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateActivity'
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateActivityResponse'
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: number
                    example: 400
                  error:
                    type: string
                    example: نام باید رشته باشد.
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        403:
          $ref: '#/components/schemas/ForbiddenResponse'
        404:
          $ref: '#/components/schemas/ActivityNotFoundResponse'

    delete:
      summary: Delete a activity.
      tags: ['Activity']
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the activity.
          schema:
            type: number
            example: 1
      responses:
        200:
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteActivityResponse'
        401:
          $ref: '#/components/schemas/UnauthorizedResponse'
        403:
          $ref: '#/components/schemas/ForbiddenResponse'
        404:
          $ref: '#/components/schemas/ActivityNotFoundResponse'
